-- ============================================================================
-- 🛡️ RISKGUARD AI: Banking Risk, Fraud & Regulatory Intelligence Copilot
-- Challenge: Hack2Skill × Snowflake CoCo CLI 2026
-- Script 01: Core Database, Schema & Financial Tables Setup
-- ============================================================================

-- Create Warehouse & Database
CREATE WAREHOUSE IF NOT EXISTS RISKGUARD_WH 
    WITH WAREHOUSE_SIZE = 'XSMALL' 
    AUTO_SUSPEND = 60 
    AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS RISKGUARD;
USE DATABASE RISKGUARD;

-- Schemas for Data Architecture
CREATE SCHEMA IF NOT EXISTS RISKGUARD.DATA;
CREATE SCHEMA IF NOT EXISTS RISKGUARD.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS RISKGUARD.GOVERNANCE;

USE SCHEMA RISKGUARD.DATA;

-- 1. CUSTOMER TABLE
CREATE OR REPLACE TABLE CUSTOMER (
    CUSTOMER_ID STRING PRIMARY KEY,
    CUSTOMER_TYPE STRING NOT NULL, -- 'RETAIL', 'CORPORATE', 'MSME', 'HNWI'
    CUSTOMER_NAME STRING NOT NULL,
    DOB DATE,
    COUNTRY STRING DEFAULT 'IN',
    CITY STRING,
    OCCUPATION STRING,
    ANNUAL_INCOME NUMBER(18,2),
    CUSTOMER_SINCE DATE,
    RISK_RATING STRING, -- 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'
    KYC_STATUS STRING   -- 'VERIFIED', 'PENDING_RE_KYC', 'FLAGGED'
);

-- 2. ACCOUNT TABLE
CREATE OR REPLACE TABLE ACCOUNT (
    ACCOUNT_ID STRING PRIMARY KEY,
    CUSTOMER_ID STRING NOT NULL,
    ACCOUNT_TYPE STRING NOT NULL, -- 'SAVINGS', 'CURRENT', 'TERM_LOAN', 'OVERDRAFT'
    CURRENCY STRING DEFAULT 'INR',
    OPEN_DATE DATE,
    CURRENT_BALANCE NUMBER(18,2),
    AVAILABLE_BALANCE NUMBER(18,2),
    STATUS STRING, -- 'ACTIVE', 'DORMANT', 'FROZEN', 'SURVEILLANCE'
    BRANCH_ID STRING,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

-- 3. COUNTERPARTY TABLE
CREATE OR REPLACE TABLE COUNTERPARTY (
    COUNTERPARTY_ID STRING PRIMARY KEY,
    NAME STRING NOT NULL,
    COUNTRY STRING DEFAULT 'IN',
    INDUSTRY STRING,
    RISK_RATING STRING,
    SANCTIONS_FLAG BOOLEAN DEFAULT FALSE
);

-- 4. TRANSACTION TABLE
CREATE OR REPLACE TABLE TRANSACTION (
    TRANSACTION_ID STRING PRIMARY KEY,
    ACCOUNT_ID STRING NOT NULL,
    CUSTOMER_ID STRING NOT NULL,
    TRANSACTION_TS TIMESTAMP_NTZ NOT NULL,
    TRANSACTION_TYPE STRING, -- 'TRANSFER', 'DEPOSIT', 'WITHDRAWAL', 'MERCHANT_PAYMENT'
    DIRECTION STRING,        -- 'INBOUND', 'OUTBOUND'
    AMOUNT NUMBER(18,2) NOT NULL,
    CURRENCY STRING DEFAULT 'INR',
    CHANNEL STRING,          -- 'IMPS', 'RTGS', 'NEFT', 'UPI', 'CASH', 'WIRE'
    MERCHANT_CATEGORY STRING,
    COUNTERPARTY_ID STRING,
    COUNTERPARTY_COUNTRY STRING DEFAULT 'IN',
    DEVICE_ID STRING,
    IP_COUNTRY STRING DEFAULT 'IN',
    GEO_LAT FLOAT,
    GEO_LON FLOAT,
    TRANSACTION_STATUS STRING DEFAULT 'SUCCESS',
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (COUNTERPARTY_ID) REFERENCES COUNTERPARTY(COUNTERPARTY_ID)
);

-- 5. LOAN (CREDIT RISK)
CREATE OR REPLACE TABLE LOAN (
    LOAN_ID STRING PRIMARY KEY,
    CUSTOMER_ID STRING NOT NULL,
    PRODUCT_TYPE STRING, -- 'COMMERCIAL_TERM_LOAN', 'WORKING_CAPITAL', 'HOUSING', 'VEHICLE'
    PRINCIPAL_AMOUNT NUMBER(18,2),
    OUTSTANDING_AMOUNT NUMBER(18,2),
    INTEREST_RATE FLOAT,
    TENURE_MONTHS INTEGER,
    START_DATE DATE,
    MATURITY_DATE DATE,
    STATUS STRING, -- 'ACTIVE', 'SMA_0', 'SMA_1', 'SMA_2', 'NPA', 'CLOSED'
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

-- 6. LOAN REPAYMENT (CREDIT EWS)
CREATE OR REPLACE TABLE LOAN_REPAYMENT (
    PAYMENT_ID STRING PRIMARY KEY,
    LOAN_ID STRING NOT NULL,
    DUE_DATE DATE,
    PAYMENT_DATE DATE,
    DUE_AMOUNT NUMBER(18,2),
    PAID_AMOUNT NUMBER(18,2),
    DAYS_PAST_DUE INTEGER DEFAULT 0,
    FOREIGN KEY (LOAN_ID) REFERENCES LOAN(LOAN_ID)
);

-- 7. LIQUIDITY POSITION (BASEL III / TREASURY)
CREATE OR REPLACE TABLE LIQUIDITY_POSITION (
    POSITION_DATE DATE NOT NULL,
    BUSINESS_UNIT STRING NOT NULL,
    HQLA NUMBER(18,2),               -- High Quality Liquid Assets
    CASH_INFLOW NUMBER(18,2),
    CASH_OUTFLOW NUMBER(18,2),
    NET_CASH_FLOW NUMBER(18,2),
    DEPOSIT_BALANCE NUMBER(18,2),
    SHORT_TERM_FUNDING NUMBER(18,2),
    LCR FLOAT,                        -- Liquidity Coverage Ratio (%)
    NSFR FLOAT,                       -- Net Stable Funding Ratio (%)
    PRIMARY KEY (POSITION_DATE, BUSINESS_UNIT)
);

-- 8. REGULATORY DOCUMENTS CORPUS (FOR CORTEX SEARCH)
CREATE OR REPLACE TABLE REGULATORY_DOCUMENTS (
    DOCUMENT_ID STRING PRIMARY KEY,
    DOCUMENT_TYPE STRING, -- 'REGULATION', 'CIRCULAR', 'POLICY', 'TYPOLOGY'
    REGULATOR STRING,     -- 'RBI', 'FATF', 'FIU_IND', 'BCBS', 'FINCEN'
    JURISDICTION STRING,  -- 'INDIA', 'GLOBAL', 'USA'
    TITLE STRING,
    SECTION STRING,
    EFFECTIVE_DATE DATE,
    DOCUMENT_VERSION STRING,
    TEXT STRING           -- Searchable corpus indexed by Snowflake Cortex Search
);

USE SCHEMA RISKGUARD.GOVERNANCE;

-- 9. RISK EVIDENCE TABLE (THE EXPLAINABLE GROUNDED EVIDENCE CORE)
CREATE OR REPLACE TABLE RISK_EVIDENCE (
    EVIDENCE_ID STRING PRIMARY KEY,
    CASE_ID STRING NOT NULL,
    EVIDENCE_TYPE STRING, -- 'TRANSACTION', 'CUSTOMER', 'POLICY', 'METRIC', 'COUNTERPARTY'
    SOURCE_TABLE STRING,
    SOURCE_ID STRING,
    EVIDENCE_TEXT STRING,
    RISK_SCORE FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY STRING DEFAULT 'CORTEX_RISK_ENGINE'
);

-- 10. RISK CASE TABLE (CASE MANAGEMENT WORKFLOW)
CREATE OR REPLACE TABLE RISK_CASE (
    CASE_ID STRING PRIMARY KEY,
    CUSTOMER_ID STRING NOT NULL,
    RISK_DOMAIN STRING,   -- 'AML_FRAUD', 'CREDIT_RISK', 'LIQUIDITY_RISK'
    RISK_SCORE FLOAT,
    SEVERITY STRING,      -- 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'
    STATUS STRING,        -- 'DETECTED', 'INVESTIGATING', 'ESCALATED', 'REVIEWED', 'CLOSED'
    FINDING TEXT,
    RECOMMENDATION TEXT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    REVIEWER STRING,
    AUDIT_HASH STRING
);
